"""Assemble glslang's human-readable SPIR-V disassembly back into a binary module.

Unity "Compile and show code" for Vulkan prints SPIR-V the way `glslang -H` does:

    // Module Version 10000
    // Generated by (magic number): 8000a
    // Id's are bound by 41
                  Capability Shader
      11(vX):     10(ptr) Variable Input
          32:    7(fvec4) ExtInst 1(GLSL.std.450) 13(Sin) 31

malioc needs a SPIR-V binary (.vert.spv / .frag.spv). This module encodes the
text word by word with the SPIR-V grammar (spirv.core.grammar.json), so the
output is the same module glslang produced: ids, constants (printed as raw bits)
and the header are kept as is.

The grammar ships with the Android NDK (also inside Unity's AndroidPlayer);
set SPIRV_GRAMMAR to its path if it is not found automatically.
"""
import glob
import json
import os
import re
import struct

_GRAMMAR_GLOBS = [
    r"C:\Program Files\Unity\Hub\Editor\*\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\sources"
    r"\third_party\shaderc\third_party\spirv-tools\external\spirv-headers\include\spirv\unified1\spirv.core.grammar.json",
    os.path.join(os.environ.get("LOCALAPPDATA", ""), r"Android\Sdk\ndk\*\sources\third_party\shaderc\third_party"
                 r"\spirv-tools\external\spirv-headers\include\spirv\unified1\spirv.core.grammar.json"),
]
MAGIC = 0x07230203
ID_KINDS = {"IdResultType", "IdResult", "IdRef", "IdMemorySemantics", "IdScope"}
INT_KINDS = {"LiteralInteger", "LiteralExtInstInteger"}
# TypeImage: glslang prints "2D sampled format:Unknown" instead of five operands
IMAGE_FLAGS = {"depth": 0, "array": 1, "multi-sampled": 2}
IMAGE_SAMPLED = {"runtime": 0, "sampled": 1, "nonsampled": 2}

_TOKEN = re.compile(r'"(?:[^"\\]|\\.)*"|[^\s"(]+(?:\([^)]*\))?')
_CASE = re.compile(r"^\s*case (-?\d+): (\d+)\s*$")
_LINE = re.compile(r"^\s*(?:(\d+)(?:\([^)]*\))?:)?\s*(?:(\d+)(?:\([^)]*\))?\s+)?([A-Z][A-Za-z0-9_]*)\b(.*)$")


class SpirvTextError(ValueError):
    pass


def find_grammar():
    p = os.environ.get("SPIRV_GRAMMAR")
    if p and os.path.exists(p):
        return p
    for g in _GRAMMAR_GLOBS:
        hits = sorted(glob.glob(g))
        if hits:
            return hits[-1]
    raise SpirvTextError("spirv.core.grammar.json not found: install the Android NDK (Unity Android module) "
                         "or set SPIRV_GRAMMAR")


class Grammar:
    def __init__(self, path=None):
        with open(path or find_grammar(), encoding="utf-8") as f:
            g = json.load(f)
        self.ops = {i["opname"][2:]: i for i in g["instructions"]}
        self.kinds = {}
        for k in g["operand_kinds"]:
            enums = {}
            for e in k.get("enumerants", []):
                v = e["value"]
                enums[e["enumerant"]] = (int(v, 16) if isinstance(v, str) else v, e.get("parameters", []))
                for alias in e.get("aliases", []):
                    enums[alias] = enums[e["enumerant"]]
            self.kinds[k["kind"]] = (k["category"], enums)


_grammar = None


def grammar():
    global _grammar
    if _grammar is None:
        _grammar = Grammar()
    return _grammar


def _int(tok):
    return int(tok.split("(", 1)[0])


def _string_words(tok):
    s = tok[1:-1].replace('\\"', '"').replace("\\\\", "\\").encode("utf-8") + b"\0"
    s += b"\0" * (-len(s) % 4)
    return list(struct.unpack(f"<{len(s) // 4}I", s))


class _Assembler:
    def __init__(self, g):
        self.g = g

    def operand(self, kind, toks, out):
        """Encode one operand of `kind` from the front of toks."""
        cat, enums = self.g.kinds[kind]
        if kind in ID_KINDS or kind in INT_KINDS:
            out.append(_int(toks.pop(0)) & 0xFFFFFFFF)
        elif kind == "LiteralString":
            out.extend(_string_words(toks.pop(0)))
        elif kind == "LiteralContextDependentNumber":
            while toks:  # one printed number per word (64-bit constants print two)
                out.append(_int(toks.pop(0)) & 0xFFFFFFFF)
        elif kind == "LiteralSpecConstantOpInteger":
            t = toks.pop(0)
            out.append(self.g.ops[t]["opcode"] if t in self.g.ops else _int(t))
        elif kind.startswith("Pair"):  # two ids or 32-bit literals
            for _ in range(2):
                out.append(_int(toks.pop(0)) & 0xFFFFFFFF)
        elif cat == "ValueEnum":
            t = toks.pop(0)
            if t not in enums:
                raise SpirvTextError(f"unknown {kind} '{t}'")
            v, params = enums[t]
            out.append(v)
            for p in params:
                self.operand(p["kind"], toks, out)
        elif cat == "BitEnum":
            mask, names = 0, []
            while toks and toks[0] in enums:
                names.append(toks.pop(0))
                mask |= enums[names[-1]][0]
            if not names:
                raise SpirvTextError(f"expected {kind}, got '{toks[0] if toks else ''}'")
            out.append(mask)
            for bit in range(32):  # parameters follow in bit order
                for n in names:
                    v, params = enums[n]
                    if v == 1 << bit:
                        for p in params:
                            self.operand(p["kind"], toks, out)
        else:
            raise SpirvTextError(f"unsupported operand kind {kind}")

    def fits(self, kind, tok):
        cat, enums = self.g.kinds[kind]
        if cat in ("ValueEnum", "BitEnum"):
            return tok in enums
        if kind == "LiteralString":
            return tok.startswith('"')
        return tok[0].isdigit() or tok[0] == "-"

    def instruction(self, op, result, rtype, rest):
        if op not in self.g.ops:
            raise SpirvTextError(f"unknown instruction '{op}'")
        info = self.g.ops[op]
        toks = _TOKEN.findall(rest)
        words = []
        if op == "TypeImage":
            words += [result, _int(toks.pop(0)), self.g.kinds["Dim"][1][toks.pop(0)][0]]
            flags = [0, 0, 0]
            while toks and toks[0] in IMAGE_FLAGS:
                flags[IMAGE_FLAGS[toks.pop(0)]] = 1
            words += flags + [IMAGE_SAMPLED[toks.pop(0)]]
            words.append(self.g.kinds["ImageFormat"][1][toks.pop(0).split(":", 1)[1]][0])
            if toks:
                words.append(self.g.kinds["AccessQualifier"][1][toks.pop(0)][0])
        else:
            for spec in info.get("operands", []):
                kind, q = spec["kind"], spec.get("quantifier")
                if kind == "IdResultType":
                    words.append(rtype)
                elif kind == "IdResult":
                    words.append(result)
                elif q == "*":
                    while toks:
                        self.operand(kind, toks, words)
                elif q == "?":
                    if toks and self.fits(kind, toks[0]):
                        self.operand(kind, toks, words)
                else:
                    if not toks:
                        raise SpirvTextError(f"{op}: missing operand {kind}")
                    self.operand(kind, toks, words)
        if toks:
            raise SpirvTextError(f"{op}: unparsed operands {toks}")
        return [(len(words) + 1) << 16 | info["opcode"]] + words


def assemble(text, g=None):
    """glslang -H text of one shader stage -> SPIR-V binary (bytes)."""
    g = g or grammar()
    asm = _Assembler(g)
    version, generator, bound = 0x10000, 0, 0
    # glslang prints the targets of Switch on their own lines ("case 10: 43"):
    # append them to the Switch line as (literal, label) operand pairs
    lines = []
    for n, line in enumerate(text.splitlines(), 1):
        m = _CASE.match(line)
        if m and lines:
            lines[-1] = (lines[-1][0], f"{lines[-1][1]} {m.group(1)} {m.group(2)}")
        else:
            lines.append((n, line))
    body, max_id = [], 0
    for n, line in lines:
        s = line.strip()
        if not s:
            continue
        if s.startswith("//"):
            if m := re.match(r"// Module Version (\w+)", s):
                version = int(m.group(1), 16)
            elif m := re.match(r"// Generated by \(magic number\): (\w+)", s):
                generator = int(m.group(1), 16)
            elif m := re.match(r"// Id's are bound by (\d+)", s):
                bound = int(m.group(1))
            continue
        m = _LINE.match(line)
        if not m:
            raise SpirvTextError(f"line {n}: cannot parse: {s}")
        result, rtype, op, rest = m.groups()
        try:
            words = asm.instruction(op, int(result) if result else None, int(rtype) if rtype else None, rest)
        except (SpirvTextError, KeyError, IndexError, ValueError) as e:
            raise SpirvTextError(f"line {n}: {e}: {s}") from None
        body += words
        if result:
            max_id = max(max_id, int(result))
    if not body:
        raise SpirvTextError("no SPIR-V instructions")
    header = [MAGIC, version, generator, max(bound, max_id + 1), 0]
    return struct.pack(f"<{len(header) + len(body)}I", *header, *body)
